data <- read.table("household_power_consumption.txt",header = T,sep = ";")

p3<- subset(data,data$Date=="1/2/2007" | data$Date=="2/2/2007")
TimeDate <- strptime(paste(p3$Date, p3$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
sm1 <- as.numeric(p3$Sub_metering_1)
sm2 <- as.numeric(p3$Sub_metering_2)
sm3 <- as.numeric(p3$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(TimeDate, sm1, type="l", xlab="", ylab="Energy sub metering")
lines(TimeDate,sm2,type="l", col="red")
lines(TimeDate,sm3,type="l", col="blue")
legend("topright",legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2, col=c("black", "red", "blue"))
dev.off()
